import os
import asyncio
import agent
import utils
import json
import re
import ast
from types import SimpleNamespace
from datetime import datetime
from dotenv import load_dotenv
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from google.cloud import firestore
from linkedin_tracker import LinkedInTracker

load_dotenv()
REFERENCE_DOMAIN = "navistone.com"
CACHE_COLLECTION = "discovery_cache"

try:
    project_id = os.getenv("PROJECT_ID")
    db = firestore.Client(project=project_id) if project_id else firestore.Client()
except Exception:
    db = None


# --- HELPER: POST TO SLACK ---
def post_update_to_slack(company_name, change_summary, deep_dive_url=None):
    token = os.environ.get("SLACK_BOT_TOKEN")
    channel = os.environ.get("SLACK_CHANNEL_ID")
    if not token or not channel:
        return
    client = WebClient(token=token)
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🚨 Competitor Update: {company_name}",
                "emoji": True,
            },
        },
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"{change_summary}"}},
    ]
    if deep_dive_url:
        blocks.append(
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"🔗 <{deep_dive_url}|Visit Website> | 📅 {datetime.now().strftime('%Y-%m-%d')}",
                    }
                ],
            }
        )
    try:
        client.chat_postMessage(
            channel=channel, blocks=blocks, text=f"Update detected for {company_name}"
        )
    except SlackApiError as e:
        print(f"❌ Slack Error: {e.response['error']}")


# --- HELPER: SEND EMAIL ---
def send_update_email(company_name, change_summary, deep_dive_url=None):
    if not db:
        return
    try:
        subscribers = (
            db.collection("subscribers").where("status", "==", "active").stream()
        )
        recipients = [doc.to_dict()["email"] for doc in subscribers]
    except Exception:
        return
    if not recipients:
        return

    html_content = f"""
    <html><body style="font-family: Arial, sans-serif; color: #333;"><div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;"><div style="background-color: #0044cc; color: white; padding: 20px;"><h2 style="margin: 0;">🚨 Competitor Alert: {company_name}</h2></div><div style="padding: 20px;"><p style="font-size: 16px; line-height: 1.5;"><strong>Analyst Note:</strong><br>{change_summary.replace(chr(10), '<br>')}</p><hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;"><p style="font-size: 12px; color: #777;">Report generated by Marketing Analyst Agent</p></div></div></body></html>
    """
    for email in recipients:
        utils.send_email(
            subject=f"⚠️ Update: {company_name} Strategy Shift",
            recipient_email=email,
            body_text=change_summary,
            html_body=html_content,
        )


# --- HELPER: BASELINE REPORT ---
def send_baseline_report(new_subscriber_email):
    print(f"📨 Generating Baseline Report for {new_subscriber_email}...")
    if not db:
        return
    competitor_data = []
    try:
        track_docs = db.collection("competitors").stream()
        for doc in track_docs:
            data = doc.to_dict()
            domain = doc.id
            if REFERENCE_DOMAIN.lower() in domain.lower():
                continue
            content = data.get("content", {})
            val_prop = content.get("value_proposition", "Pending Analysis...")
            if len(val_prop) > 150:
                val_prop = val_prop[:150] + "..."
            competitor_data.append(
                {
                    "name": data.get("name", domain.split(".")[0].capitalize()),
                    "domain": domain,
                    "val_prop": val_prop,
                }
            )
    except Exception as e:
        print(f"❌ Error gathering baseline: {e}")
        return

    if not competitor_data:
        return
    list_items = ""
    for comp in competitor_data:
        list_items += f'<li style="margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 10px;"><strong style="font-size: 16px;">{comp["name"]}</strong> <a href="https://{comp["domain"]}" style="color: #0044cc; text-decoration: none; font-size: 12px;">(Visit)</a><br><span style="color: #555; font-size: 14px; font-style: italic;">{comp["val_prop"]}</span></li>'

    html_content = f"""
    <html><body style="font-family: Arial, sans-serif; color: #333;"><div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;"><div style="background-color: #2c3e50; color: white; padding: 25px;"><h1 style="margin: 0; font-size: 22px;">Welcome to Market Intel</h1><p style="margin: 5px 0 0 0; opacity: 0.8;">Your surveillance feed is active.</p></div><div style="padding: 25px;"><p>We are tracking <strong>{len(competitor_data)} competitors</strong> for you:</p><ul style="padding-left: 20px;">{list_items}</ul></div></div></body></html>
    """
    utils.send_email(
        subject="📈 Baseline Report: Active Surveillance Targets",
        recipient_email=new_subscriber_email,
        body_text="Your baseline report is attached (HTML).",
        html_body=html_content,
    )
    print(f"✅ Baseline report sent to {new_subscriber_email}")


# --- CORE LOGIC: DISCOVER ---
async def discover_competitors(target_domain):
    print(f"🔭 Starting Deep Discovery for {target_domain}...")
    if db:
        doc = db.collection(CACHE_COLLECTION).document(target_domain).get()
        if doc.exists:
            return doc.to_dict().get("competitors", [])

    # FETCH ALREADY TRACKED DOMAINS TO EXCLUDE THEM
    tracked_domains = []
    if db:
        docs = db.collection("competitors").stream()
        tracked_domains = [d.id for d in docs]

    banned_list = ", ".join(tracked_domains)

    prompt = (
        f"Identify top 5 direct competitors for {target_domain}. "
        f"ALREADY TRACKED (DO NOT RETURN THESE): {banned_list}.\n"
        f"STEP 1: Analyze {target_domain} industry.\n"
        f"STEP 2: Find 5 NEW competitors.\n"
        f"STEP 3: Return JSON keys: 'industry_profile', 'competitors' (list of {{name, domain, reason}})."
    )

    try:
        raw_response = await agent.run_agent_turn(prompt, [], headless=True)
        # ... (Parsing logic similar to refresh below) ...
        # For brevity reusing the robust parsing block from refresh
        data = {}
        json_match = re.search(r"\{.*\}", raw_response, re.DOTALL)
        if json_match:
            try:
                data = json.loads(json_match.group(0))
            except:
                try:
                    data = ast.literal_eval(json_match.group(0))
                except:
                    return []

        valid_competitors = []
        for comp in data.get("competitors", []):
            if not comp.get("domain"):
                clean_name = comp.get("name", "").replace(" ", "").lower()
                comp["domain"] = f"{clean_name}.com"

            # Check against tracked list again
            norm_domain = comp["domain"].lower().replace("www.", "").split("/")[0]
            if any(t in norm_domain for t in tracked_domains):
                continue

            valid_competitors.append(comp)

        if db and valid_competitors:
            db.collection(CACHE_COLLECTION).document(target_domain).set(
                {
                    "industry_profile": data.get("industry_profile", "Unknown"),
                    "competitors": valid_competitors,
                    "dismissed": [],
                    "last_updated": datetime.now(),
                }
            )
            return valid_competitors
        return []
    except Exception as e:
        print(f"❌ Discovery failed: {e}")
        return []


# --- CORE LOGIC: REFRESH (UPDATED EXCLUSION) ---
async def refresh_competitors(target_domain, target_count=5, retry_level=0):
    print(f"🔄 Refreshing list for {target_domain} (Attempt: {retry_level})...")
    if not db:
        return []

    doc_ref = db.collection(CACHE_COLLECTION).document(target_domain)
    doc = doc_ref.get()

    existing_competitors = []
    dismissed_domains = []
    industry_profile = "a specific industry"

    if doc.exists:
        data = doc.to_dict()
        existing_competitors = data.get("competitors", [])
        dismissed_domains = data.get("dismissed", [])
        industry_profile = data.get("industry_profile", industry_profile)

    # 1. FETCH ACTIVELY TRACKED DOMAINS (Global Ban List)
    active_tracked_domains = []
    active_docs = db.collection("competitors").stream()
    active_tracked_domains = [d.id.lower() for d in active_docs]

    # Normalize helpers
    def normalize(d):
        return (
            d.lower()
            .replace("https://", "")
            .replace("http://", "")
            .replace("www.", "")
            .split("/")[0]
        )

    current_domains_norm = [normalize(c["domain"]) for c in existing_competitors]
    dismissed_norm = [normalize(d) for d in dismissed_domains]
    active_norm = [normalize(d) for d in active_tracked_domains]

    # Combine ALL banned lists
    banned_names = (
        [c["name"] for c in existing_competitors]
        + dismissed_domains
        + active_tracked_domains
    )
    banned_list_str = ", ".join(banned_names)

    needed = target_count - len(existing_competitors)
    if needed <= 0:
        return existing_competitors

    ask_for = max(needed, 3) + (retry_level * 2)

    prompt = (
        f"Find {ask_for} NEW competitors for {target_domain} (Industry: {industry_profile}).\n"
        f"STRICTLY EXCLUDE THESE COMPANIES: {banned_list_str}.\n"
        f"INSTRUCTION: Return JSON with key 'competitors' (list of {{name, domain}})."
    )

    try:
        raw_response = await agent.run_agent_turn(prompt, [], headless=True)

        # Robust Parsing
        data = {}
        json_match = re.search(r"\{.*\}", raw_response, re.DOTALL)
        if json_match:
            try:
                data = json.loads(json_match.group(0))
            except:
                try:
                    data = ast.literal_eval(json_match.group(0))
                except:
                    data = {}

        candidates = data.get("competitors", [])
        valid_new = []

        for cand in candidates:
            # Fix Domain
            if not cand.get("domain"):
                cand["domain"] = f"{cand.get('name','').replace(' ','').lower()}.com"

            raw_domain = cand.get("domain", "").lower()
            norm = normalize(raw_domain)

            # AGGRESSIVE FILTERING
            if norm in current_domains_norm:
                continue
            if norm in dismissed_norm:
                continue
            if norm in active_norm:
                continue  # Skips already tracked stuff
            if "navistone" in norm:
                continue

            valid_new.append(cand)

        final_additions = valid_new[:needed]

        if final_additions:
            full_list = existing_competitors + final_additions
            doc_ref.update({"competitors": full_list, "last_updated": datetime.now()})
            return full_list
        else:
            # Retry if empty
            if retry_level < 2:
                return await refresh_competitors(
                    target_domain, target_count, retry_level + 1
                )
            return existing_competitors

    except Exception:
        return existing_competitors


# --- CORE LOGIC: REMOVE ---
def remove_competitor_from_cache(target_domain, competitor_domain_to_remove):
    if not db:
        return
    try:
        doc_ref = db.collection(CACHE_COLLECTION).document(target_domain)
        doc = doc_ref.get()
        if doc.exists:
            data = doc.to_dict()
            curr = data.get("competitors", [])
            dism = data.get("dismissed", [])

            new_list = [
                c for c in curr if c.get("domain") != competitor_domain_to_remove
            ]
            if competitor_domain_to_remove not in dism:
                dism.append(competitor_domain_to_remove)

            doc_ref.update({"competitors": new_list, "dismissed": dism})
    except Exception:
        pass


# --- ANALYSIS & DAILY BRIEF ---
# (Keep existing functions for check_linkedin_updates, analyze_competitor_website, run_daily_brief)
# ... Use the versions from previous turns or let me know if you need them re-pasted ...
# For brevity, I am assuming you kept the run_daily_brief logic I gave you last time.
# IMPORTANT: Ensure run_daily_brief calls the database save logic we just fixed.
async def check_linkedin_updates(company_name, domain):
    tracker = LinkedInTracker(agent_module=agent, use_mock=False)
    try:
        return await tracker.get_company_updates(company_name, domain)
    except:
        return None


async def analyze_competitor_website(domain):
    # (Same robust scrape logic as before)
    try:
        raw = await agent.run_agent_turn(
            f"Analyze {domain}. Return JSON: name, value_proposition.",
            [],
            headless=True,
        )
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            return SimpleNamespace(**json.loads(match.group(0)))
    except:
        pass
    return SimpleNamespace(
        name=domain, value_proposition="Analysis currently unavailable."
    )


async def run_daily_brief():
    # (Same as before)
    if not db:
        return
    comp_docs = db.collection("competitors").stream()
    for doc in comp_docs:
        domain = doc.id
        # ... Run analysis ...
        # ... Save to DB ...
        # ... Send alerts ...
    # Note: Ensure you include the full run_daily_brief logic here in your file!


if __name__ == "__main__":
    asyncio.run(run_daily_brief())
